const fs = require('fs');
const path = require('path');

const screensDir = path.resolve(__dirname, '..', 'app', 'screens');
const outFile = path.join(screensDir, 'index.ts');

function pascalCase(name) {
  return name
    .replace(/(^.|-./g, s => s.replace(/[-_]/, '').toUpperCase()) )
    .replace(/\.tsx?$/i, '');
}

function generate() {
  const files = fs.readdirSync(screensDir)
    .filter(f => f.endsWith('.tsx') || f.endsWith('.ts'))
    .filter(f => f !== 'index.ts');

  const exports = files.map(f => {
    const base = f.replace(/\.tsx?$/i, '');
    const name = base; // keep filename as export name (e.g. DashboardScreen)
    return `export { default as ${name} } from './${base}';`;
  }).join('\n');

  const header = `// Auto-generated by scripts/generateScreenIndex.js - do not edit by hand\n`;
  fs.writeFileSync(outFile, header + exports + '\n');
  console.log('Wrote', outFile);
}

generate();
